# Generated by Django 6.0.1 on 2026-02-24 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile', max_length=255, null=True, verbose_name='image'),
        ),
    ]
