# Generated by Django 6.0.1 on 2026-02-13 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_avater_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and underscore.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscore.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
